name: Rust

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: MIRIFLAGS="-Zmiri-disable-stacked-borrows -Zmiri-permissive-provenance" cargo miri test --all-targets
    - run: cargo install wasm-pack
    - run: cd rkyv_test && wasm-pack test --node -- --features "wasm"
